[package]
name = "befunging"
version = "0.1.0"
edition = "2021"

[dependencies]
#inkwell = { path = "../inkwell", version = "0.5.0", features = ["llvm18-0"] }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
rand = "0.8.5"
rand_derive2 = "0.1.21"

[profile.release]
debug = true
